version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz

homebrew_casks:
  - name: wt
    binaries:
      - wt
    homepage: https://github.com/zshuzh/wt
    description: Git worktree manager optimized for AI workflows
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
          end
    caveats: |
      To enable shell integration, add to your ~/.zshrc:
        eval "$(wt init zsh)"
    repository:
      owner: zshuzh
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
